name: Server

on:
  workflow_dispatch: # Run manually
  schedule:
    - cron: "0 */6 * * *" # Optional: every 6 hours

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Start Android Emulator
      - name: Start emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          profile: Pixel 4
          disable-animations: false
          script: echo "Emulator started"

      # Install Ngrok and expose ADB + Appium ports
      - name: Set up Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}  # Add your token in GitHub Secrets
          ngrok tcp 5555 &  # ADB port
          ngrok tcp 4723 &  # Appium port
          sleep 5  # Wait for Ngrok tunnels
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[] | .public_url'  # Print Ngrok URLs

      # Connect local ADB to Ngrok tunnel
      - name: Forward ADB to Ngrok
        run: |
          adb kill-server
          adb connect $(curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[] | select(.proto == "tcp") | .public_url' | sed 's/^tcp:\/\///')
          adb devices
